### ISSUE TITLE
Small letter not render properly

### ISSUE THREAD

**Issue by unishkumar** [simonneutert/jquery-google-reviews#10]
When Author name in small letter it Short name show undefined.
Any solution.

 
![image](https://user-images.githubusercontent.com/13913493/61123564-4b924a80-a4c2-11e9-8f07-f14eee98b48a.png)

![image](https://user-images.githubusercontent.com/13913493/61123405-e2123c00-a4c1-11e9-98dd-f4d7c55a0587.png)

**Comment by simonneutert** [comment]
Thank you for creating this issue :+1: 
can you please provide the name, that errors?

I will see what I can do, though right now time is scarce...

**Comment by simonneutert** [comment]
I think the "dot" is the issue here.

**Comment by simonneutert** [comment]
```javascript
    var shortenName = function(name) {
      if (name.split(" ").length > 1) {
        var shortenedName = "";
        shortenedName = name.split(" ");
        try {
                  return shortenedName[0] + " " + shortenedName[1][0] + ".";
        }
       catch (e) {
          return shortenedName[0];
       }
      }
    };
```

you find this section without the try catch statement in the source code.

maybe implement this quick fix, returning only the first name (`shortenedName[0]) on an error, make sure to either tell me, whether this worked, and or share your solution here, so I can put it to the source code so other benefit, too :heart:

**Comment by simonneutert** [comment]
cannot reproduce, I need more info, can you provide the Place ID?

**Comment by simonneutert** [comment]
1 month passed without an answer.
