### ISSUE TITLE
API not authorized

### ISSUE THREAD

**Issue by j-barot** [simonneutert/jquery-google-reviews#11]
Hi, i've got an issue with the API.
When i just activated it it works without any problem, but after a few minutes i get an error "This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console[...]" ... 
If i desactivate and reactivate the API it works again for a few minutes.

Any ideas ?

**Comment by simonneutert** [comment]
did you check the allowed ip settings?

**Comment by simonneutert** [comment]
no answer given. closing issue.
