### ISSUE TITLE
Truncate reviews text?

### ISSUE THREAD

**Issue by Eudes95** [simonneutert/jquery-google-reviews#13]
Hello,

First of all I'm not a JS tech guy, more HTML/CSS.

Any option to truncate the reviews text depending of the number of words/letters instead of "textBreakLength"? And a an ellipsis or a custom text like "Read more..."?

Thanks, have a nice day.

**Comment by simonneutert** [comment]
sorry, it took me so long to answer. this is a nice idea, I will tinker a little this evening, most parts should be already existing. fingers crossed 🤞

**Comment by simonneutert** [comment]
you could easily add another library for text shortening. 
https://codepen.io/paulobrien/pen/JXrxBg
or this
http://stephenscaff.com/articles/2018/12/readmore-js/

review text is css selectable by:
`<p class='review-text'>`

hope this helps, though I know, this is not exactly what you wanted to hear.

but this lib would outgrow itself and lose its scope a little.

**Comment by Eudes95** [comment]
Thanks Simon.

I will give it a try and see what I can do with that.

Have a nice day!

**Comment by simonneutert** [comment]
If you make it work, maybe share your story. Do you blog? Either way I would love to have it in the readme, so others can profit from your work, too. Cheers :heart:

**Comment by Eudes95** [comment]
Unfortunately Simon, as I did mention in my first message, I do not understand JS/JQuery, so I'm not the right guy if you hope any contribution, sorry for that. I have found a solution with CSS to limit the lenght of text per line, not that good, but better than nothing.

Thanks anyway for writing this nice Google reviews script:
