### ISSUE TITLE
showReviewDate 

### ISSUE THREAD

**Issue by robertraichle** [simonneutert/jquery-google-reviews#14]
Die showReviewDate auf true funzt net, kann das sein?

**Comment by simonneutert** [comment]
ja, ist untergegangen, ich schau danach 👍

**Comment by simonneutert** [comment]
ist vielleicht gefixt, konnte nicht testen, update ist im master branch und das npm paket wurde gepatcht

**Comment by simonneutert** [comment]
gibst du mir etwas feedback @robertraichle ? Dankeschön ❤️

**Comment by robertraichle** [comment]
die Funktion war ja da, halt nur auskommentiert ;)
