### ISSUE TITLE
Latest Reviews

### ISSUE THREAD

**Issue by Ace000001** [simonneutert/jquery-google-reviews#15]
Hi There! 

Awesome work putting up a basic request and html setup! But i noticed one thing when i try to use it in my project. The data you get in the response is the top 5 most relevant reviews instead of latest reviews. Is there a way to tell the API to get the latest review instead of most relevant reviews?

Cheers

**Comment by Ace000001** [comment]
Also i made a little modification to your source code. Its nice to allow callbacks once you are done rendering the reviews in case if we want to initialize other plugins or such. Consider committing the following code if you like x)

```
$.fn.googlePlaces = function(options, userCallback) {
...
   var callback = function(place, status) {
      if (status == google.maps.places.PlacesServiceStatus.OK) {
        var filteredReviews = filterReviewsByMinRating(place.reviews);
        var sortedReviews = sortReviewsByDateDesc(filteredReviews);
        if (sortedReviews.length > 0) {
          renderHeader(settings.header);
          renderReviews(sortedReviews);
          renderFooter(settings.footer);
          //custom callback added
          userCallback();
        }
      }
    }
...
}
```

Hope it help others!

**Comment by simonneutert** [comment]
hi @Ace000001 
this was discussed in issue #5 

will this help you? 
https://github.com/simonneutert/jquery-google-reviews#how-to-get-link-to-view-all-google-reviews-or-write-a-review

**Comment by Ace000001** [comment]
My issue is not the number of reviews but the order in which we get those reviews. let me explain: Lets suppose i have total 10 reviews on google. I want to get reviews 1 to 5 being latest. But what i get is something like 10, 2, 4, 8, 1, being most relevant. So the issue here is the sort order in which google send us the reviews by default. Which is not 'Latest' but most 'Relevant'.

**Comment by simonneutert** [comment]
https://stackoverflow.com/questions/39223719/to-get-more-than-5-reviews-from-google-places-api

see here, please, and get back in touch after reading @Ace000001

**Comment by simonneutert** [comment]
@Ace000001 all reviews are kept to the owner as it looks like:

https://developers.google.com/my-business/content/review-data#list_all_reviews

you could retrieve them daily and then serve them over a simple api server, but this busts the scope of this project, i am sorry
