### ISSUE TITLE
Get the avarage rating

### ISSUE THREAD

**Issue by artur-grigoryan-cgn** [simonneutert/jquery-google-reviews#16]
Hello,
is it possible to get the avarage rating of a location and nothing more?

**Comment by simonneutert** [comment]
https://developers.google.com/maps/documentation/places/web-service/details#PlaceDetailsResponses

check the "rating" attribute, I guess it is possible then

**Comment by simonneutert** [comment]
debug code around here, `console.log(place)`:  
`var filteredReviews = filterReviewsByMinRating(place.reviews);`

then drilling in, by checking "place.rating" and you should be good. please share your results @artur-grigoryan-cgn (a screenshot would be awesome 👍 )

I might add this as a feature via options then 💪

**Comment by simonneutert** [comment]
https://github.com/simonneutert/jquery-google-reviews/blob/13796aff49729c509178b2f9a490a234b9bf2dd4/jquery-google-reviews.js#L186

**Comment by artur-grigoryan-cgn** [comment]
The rating-attribute did it.
console.log(place.rating);  on line 175 did it. i can write a function for it and create a request if you want. :)

**Comment by artur-grigoryan-cgn** [comment]
![hrf](https://user-images.githubusercontent.com/16120407/111621639-821c7e80-87e8-11eb-8a5d-92ba6838daad.png)
I finished it now. Also also added the overall count of reviews and half stars if the count is a float.

**Comment by simonneutert** [comment]
i would love to receive a pull request, it makes me happy so many people enjoy the tool 🍻 ❤️

**Comment by simonneutert** [comment]
i would love to receive a pull request, it makes me happy so many people enjoy the tool 🍻 ❤️ @artur-grigoryan-cgn

**Comment by artur-grigoryan-cgn** [comment]
I wrote you an email. Could you check your mailbox? :)

**Comment by simonneutert** [comment]
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork 

und gib der repo bitte einen stern 👍
