### ISSUE TITLE
How to call new comments?

### ISSUE THREAD

**Issue by ravenwits** [simonneutert/jquery-google-reviews#17]
I've been using this plugin and it works great. But the problem is it does not fetch latest comments. I've tried to call the reviews again and and even from a different project but still the same selected reviews are the only ones that plugin fetches. So how to call new comments?

**Comment by simonneutert** [comment]
hi @RavenWits (ravens are my favourite bird btw),

please, see #15 and come back to me, if this doesn't bring any clarity.

cheers

**Comment by simonneutert** [comment]
No reply. Closed due to inactivity.
