### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [simonneutert/jquery-google-reviews#18]
Hello,

i downloaded the project and applied an api key from Google Places API. Also, i inserted a place id, but when i opened the index.html file, nothing was apperared in my browser. Is there something else that i can do?

**Comment by simonneutert** [comment]
Check what the developer console gives you, please. Check if the domain was whitelisted or if the key is in the correct product scope.

This is less of a code issue, I guess you need support setting things up.
