### ISSUE TITLE
only the newest 5 reviews are loaded

### ISSUE THREAD

**Issue by ottopic** [simonneutert/jquery-google-reviews#5]
I see only five review. The sixth have got image attached, can be it a problem?

https://goo.gl/maps/1LDmmLG5o4p

**Comment by simonneutert** [comment]
check `max_rows` setting and `min_rating`, by the way, maybe check all settings 😉

**Comment by ottopic** [comment]
Yes I do. Noting is changed.

Il giorno dom 31 mar 2019 alle 21:05 Simon Neutert <notifications@github.com>
ha scritto:

**Comment by simonneutert** [comment]
did you try setting max_rows to 10 and min_rating to 2? 

if this does not work, there is a chance google limits to last 5 items, you can check yourself by inserting up a `console.log(place.reviews);` in line 118 and inspect the result in your browser

**Comment by ottopic** [comment]
Yes, in my case it seems google limits to 5 items.

**Comment by simonneutert** [comment]
if you do not mind, please share further information, so I can try and implement a feature for more reviews :handshake:

**Comment by ottopic** [comment]
Yes I confirm that number of reviews are limited by google. I'll implement More reviews button.
