### ISSUE TITLE
Is there a way to add the user's profile picture?

### ISSUE THREAD

**Issue by SuperboltStudios** [simonneutert/jquery-google-reviews#9]
Is there a way to add the user's profile picture?

**Comment by simonneutert** [comment]
![grafik](https://user-images.githubusercontent.com/8125726/59276163-0fb75b80-8c5e-11e9-8ec3-b9b73118df16.png)

looks good, would you mind implement it and submit a pull request?

would be amazing!
simon :heart:

**Comment by simonneutert** [comment]
@SuperboltStudios see the documentation here: https://developers.google.com/places/web-service/details#PlaceDetailsResponses

**Comment by simonneutert** [comment]
@SuperboltStudios I know how to do it, can you come up with a nice way for me returning an html structure, which is highly customizable for somebody who knows enough css?

**Comment by simonneutert** [comment]
1 month passed without an answer.
